### ISSUE TITLE
Screenshot what this looks like?

### ISSUE THREAD

**Issue by rohmanhm** [moso/hyper-arc-dark-controls#1]
Hi I just jump into this repository, I'm interest with the arc-dark controls title you offers. But can you provide some screenshot what this one looks like if I installed this plugins?

**Comment by moso** [comment]
Thanks for clearing that up. I used to have a fine screenshot inside the README, however, I recently switched servers and somehow missed a couple of files that weren't moved to their right locations in the process.

If you look at the README it should look fine with an example on how the window controls looks like.

**Comment by Ornataweaver** [comment]
The screenshot on readme is corrupt.
https://camo.githubusercontent.com/bc35dc4ceeea601bc86f530adfd9827bbbdc9710/68747470733a2f2f6465762e6d6f736f2e696f2f68797065722f68797065722d6172632d6461726b2d636f6e74726f6c732f73637265656e73686f742e706e67
it says: "Error Fetching Resource"

**Comment by moso** [comment]
Thanks! I recently moved my DNS to CloudFlare, and accidentally left the SSL part to be handled by CloudFlare. But since I do that myself with letsencrypt, I had to disable the CloudFlare part.

Screenshot is working now.
