### ISSUE TITLE
titlebar issues

### ISSUE THREAD

**Issue by lewisakura** [moso/hyper-arc-dark-controls#2]
![controls](https://owo.whats-th.is/f1342c.png)
![hbmenu](https://owo.whats-th.is/0bbb79.png)

except from those two issues, good job on the theme.

**Comment by moso** [comment]
Thanks :)

I intend to make a smaller overhaul once v2 is stable.

**Comment by moso** [comment]
Fixed in 65b0f0ddadf55bd7a30d4239bb1df5483783398c

**Comment by lewisakura** [comment]
👍 Thanks!

**Comment by Bauke** [comment]
![2018-02-14_15-33-39](https://user-images.githubusercontent.com/19501722/36209644-8846d442-119c-11e8-950f-5bda55a40397.png)
Has this issue been fixed or am I on an old version?
I've tried reinstalling but it's still there, thanks in advance!

**Comment by moso** [comment]
@Bauke I'm not seeing that in either Linux or Windows, tested in both `v1.4.8` and `v2.0.0-canary.11`.

Try removing `hyper-arc-dark-controls` from `~/.hyper.js` and reboot Hyper. Then reinsert it and reboot it again. Or if you're using hpm, you can do `hpm u hyper-arc-dark-controls`, reboot Hyper, and then `hpm i hyper-arc-dark-controls`.

Either of those should get you the latest version.

The only custom CSS I use is moving the `x`-icon a few pixels down as *some* Linux distros tend to move it a bit upwards. But that particular issue isn't present in Windows or other distros. And it's not related to the whole `<ul>` like in your case.

For obvious reasons, I can't test on a Mac.

Do report back if the issue persists, and create a new issue as it's not related to the hamburger-issue.
