### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by DavidStrada** [moso/hyper-arc-dark-controls#3]
What theme are you using on your screenshot ?

could you provide your `hyper.js` config file ?

**Comment by moso** [comment]
That would be the [hyperterm-atom-dark](https://www.npmjs.com/package/hyperterm-atom-dark) theme.

Config: [Gist](https://gist.github.com/moso/94dc06a4db0edd4741e0063cd5e83c47).

Font is from [powerline/fonts](https://github.com/powerline/fonts).
