### ISSUE TITLE
Window Controls offset

### ISSUE THREAD

**Issue by Bauke** [moso/hyper-arc-dark-controls#4]
As shown in [issue #2](https://github.com/moso/hyper-arc-dark-controls/issues/2#issuecomment-365625485) the window controls are offset by a few pixels. 

I've tried reinstalling Hyper and using a default config and then adding/removing the plugin while Hyper isn't running but to no avail.

![2018-02-14_15-33-39](https://user-images.githubusercontent.com/19501722/36212451-4ac52a3a-11a4-11e8-9396-20e28ffb4860.png)

Edit: I've just changed the border color from Hyper and it shows there's a pixel between the border and the controls.

![sharex_2018-02-14_16-59-40](https://user-images.githubusercontent.com/19501722/36214008-86b939ce-11a8-11e8-882f-d8765dd26642.png)

**Comment by moso** [comment]
Right....
After uninstalling every plugin, and only with this plugin loaded, I get the same issue.

I'll have a working fix up later. Thanks for the report!

**Comment by moso** [comment]
Fixed in 57b7acc
