### ISSUE TITLE
Positioning Question

### ISSUE THREAD

**Issue by Koned** [moso/hyper-arc-dark-controls#5]
Hi Morten,
First, thanks for working on hyper-arc-dark-controls! I had a quick question though. This is what my Hyper currently looks like:  
<img width="760" alt="screenshot 2018-02-25 17 19 59" src="https://user-images.githubusercontent.com/36646507/36647204-2143e192-1a50-11e8-904d-e1c500dd858d.png">
 I'm on Mac so I'm not sure if it's just a Mac thing but is it possible to move the arc-dark-controls on the top right of the tab bar? 

This is my current config (sorry if it's a mess... still learning to code, etc.):

`// Future versions of Hyper may add additional config options,
// which will not automatically be merged into this file.
// See https://hyper.is#cfg for all currently supported options.

module.exports = {
  config: {
  	hyperTabs: {
		trafficButtons: false,
		border: true,
		tabIconsColored: true,
		activityColor: 'cyan',
		closeAlign: 'left',
		},

	hyperlinks: {
		clickAction: 'open',
		defaultBrowser: true,
	},

    // default font size in pixels for all tabs
    fontSize: 12,

    // font family with optional fallbacks
    fontFamily: 'Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',

    // terminal cursor background color and opacity (hex, rgb, hsl, hsv, hwb or cmyk)
    cursorColor: 'rgba(248,28,229,0.8)',

    // `BEAM` for |, `UNDERLINE` for _, `BLOCK` for █
    cursorShape: 'BLOCK',

    // set to true for blinking cursor
    cursorBlink: false,

    // color of the text
    foregroundColor: '#fff',

    // terminal background color
    backgroundColor: '#000',

    // border color (window, tabs)
    borderColor: '#333',

    // custom css to embed in the main window
    css: '',

    // custom css to embed in the terminal window
    termCSS: '',

    // set to `true` (without backticks) if you're using a Linux setup that doesn't show native menus
    // default: `false` on Linux, `true` on Windows (ignored on macOS)
    showHamburgerMenu: '',

    // set to `false` if you want to hide the minimize, maximize and close buttons
    // additionally, set to `'left'` if you want them on the left, like in Ubuntu
    // default: `true` on windows and Linux (ignored on macOS)
    showWindowControls: 'true',

    // custom padding (css format, i.e.: `top right bottom left`)
    padding: '7px 5px',

    // the full list. if you're going to provide the full color palette,
    // including the 6 x 6 color cubes and the grayscale map, just provide
    // an array here instead of a color map object
    colors: {
      black: '#000000',
      red: '#ff0000',
      green: '#33ff00',
      yellow: '#ffff00',
      blue: '#0066ff',
      magenta: '#cc00ff',
      cyan: '#00ffff',
      white: '#d0d0d0',
      lightBlack: '#808080',
      lightRed: '#ff0000',
      lightGreen: '#33ff00',
      lightYellow: '#ffff00',
      lightBlue: '#0066ff',
      lightMagenta: '#cc00ff',
      lightCyan: '#00ffff',
      lightWhite: '#ffffff'
    },

    // the shell to run when spawning a new session (i.e. /usr/local/bin/fish)
    // if left empty, your system's login shell will be used by default
    // make sure to use a full path if the binary name doesn't work
    // (e.g `C:\\Windows\\System32\\bash.exe` instead of just `bash.exe`)
    // if you're using powershell, make sure to remove the `--login` below
    shell: '',

    // for setting shell arguments (i.e. for using interactive shellArgs: ['-i'])
    // by default ['--login'] will be used
    shellArgs: ['--login'],

    // for environment variables
    env: {},

    // set to false for no bell
    bell: false,

    // if true, selected text will automatically be copied to the clipboard
    copyOnSelect: 'true',
	quickEdit: 'true',

    hyperBorder: {
    	animate: true,
    		duration: '9s',
    	borderColors: ['random','random'],
 	  	borderWidth: '3px'
		}
        
    // if true, on right click selected text will be copied or pasted if no
    // selection is present (true by default on Windows)
    // quickEdit: true

    // URL to custom bell
    // bellSoundURL: 'http://example.com/bell.mp3',

    // for advanced config flags please refer to https://hyper.is/#cfg
  },

  // a list of plugins to fetch and install from npm
  // format: [@org/]project[#version]
  // examples:
  //   `hyperpower`
  //   `@company/project`
  //   `project#1.0.1`
plugins: [
  'hyper-material-theme',
  'hyper-tabs-enhanced',
  'hyper-blink',
  'hyper-statusline',
  'hyperpower',
  'hyperyellow',
  'hyperlinks',
  'hyperborder',
  'hyper-quickssh',
  'space-pull',
  'hypergravity',
  'hyperterm-paste',
  "hyper-arc-dark-controls"
],

  // in development, you can create a directory under
  // `~/.hyper_plugins/local/` and include it here
  // to load it and avoid it being `npm install`ed
  localPlugins: []
};
`

Thanks!

**Comment by moso** [comment]
Oh wow...
Well, I'll look into it. But the plugin might have to be rewritten completely if it's going to take all sorts of plugins into account.

The immediate positioning problem can be fixed, however the problem will then move to the width of the window header as it's too wide.

But again, I'll see what I can do to fix it.

**Comment by Koned** [comment]
Oh wow... I didn't think about the issue with the width of the window header. Thanks for trying to fix it though :)

**Comment by moso** [comment]
The off-positioning should have been fixed with 9809ecf45a9614af1a8b5dbf20db4d7e177dd8f2.

However, I'll keep this issue open to track the header issue.

**Comment by moso** [comment]
Seems this is fixed since there hasn't been new reports for 24 months. Closing.
